# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: malcolms_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16malcolms_service.proto\x12\x04grpc\"\x14\n\x04UUID\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"@\n\nBoundaries\x12\x11\n\tdimension\x18\x01 \x01(\x03\x12\x0e\n\x06infima\x18\x02 \x03(\x01\x12\x0f\n\x07suprema\x18\x03 \x03(\x01\"N\n\x0bWalkRequest\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x16\n\x0estarting_point\x18\x01 \x03(\x01\x12\x19\n\x11number_of_samples\x18\x02 \x01(\x03\",\n\x07Samples\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x01\"J\n\x0bTrueSamples\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x01\x12\x18\n\x10posterior_values\x18\x03 \x03(\x01\x32\xa4\x01\n\tAppraiser\x12/\n\rPutBoundaries\x12\x10.grpc.Boundaries\x1a\n.grpc.UUID\"\x00\x12\x38\n\x13RegisterTrueSamples\x12\x11.grpc.TrueSamples\x1a\n.grpc.UUID\"\x00(\x01\x12,\n\x04Walk\x12\x11.grpc.WalkRequest\x1a\r.grpc.Samples\"\x00\x30\x01\x42,Z*github.com/p-nordmann/malcolm-sampler/grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'malcolms_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/p-nordmann/malcolm-sampler/grpc'
  _UUID._serialized_start=32
  _UUID._serialized_end=52
  _BOUNDARIES._serialized_start=54
  _BOUNDARIES._serialized_end=118
  _WALKREQUEST._serialized_start=120
  _WALKREQUEST._serialized_end=198
  _SAMPLES._serialized_start=200
  _SAMPLES._serialized_end=244
  _TRUESAMPLES._serialized_start=246
  _TRUESAMPLES._serialized_end=320
  _APPRAISER._serialized_start=323
  _APPRAISER._serialized_end=487
# @@protoc_insertion_point(module_scope)
